import type { DesignTemplate } from "./types";

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    blurb: "Magazine-grade with dramatic serif display type and generous negative space.",
    mood: ["literary", "authoritative", "considered", "print-inspired"],
    palette: {
      primary: "#111111",
      accent: "#B5432C",
      bg: "#F6F2EA",
      surface: "#FFFFFF",
      text: "#141414",
      muted: "#6B6358",
    },
    typography: {
      heading: "Fraunces",
      body: "Inter",
      headingWeight: 700,
      bodyWeight: 400,
      headingStyle: "normal",
      headingCase: "normal",
    },
    layoutDNA:
      "Hero is full-width with a centered headline at ~11vw, small eyebrow kicker above, single short paragraph below, and a thin underlined text CTA rather than a button. Section headings sit against wide left margin rules; body copy lives in a 60ch column. Uses drop caps for section openers and small caps for labels.",
    bestFor: ["publishers", "law firms", "non-profits", "portfolios"],
  },
  {
    id: "dark-monolith",
    name: "Dark Luxury Monolith",
    blurb: "Pure-black canvas, hairline dividers, restrained gold accents.",
    mood: ["premium", "nocturnal", "engineered", "quiet"],
    palette: {
      primary: "#FFFFFF",
      accent: "#C8A75B",
      bg: "#0A0A0A",
      surface: "#141414",
      text: "#F5F5F5",
      muted: "#8A8A8A",
    },
    typography: {
      heading: "Space Grotesk",
      body: "Inter",
      headingWeight: 500,
      bodyWeight: 400,
      headingCase: "normal",
    },
    layoutDNA:
      "Single-column, centered, narrow max-width (720px). Hero uses oversized numerical wayfinding (01 / 02 / 03). Buttons are ghost outlines with 1px gold border; primary CTA uses gold fill with black text. All dividers are 1px at 10% white opacity. Imagery is monochrome or heavily desaturated.",
    bestFor: ["luxury brands", "watchmakers", "private banks", "architecture"],
  },
  {
    id: "brutalist-grid",
    name: "Brutalist Grid",
    blurb: "Off-white canvas, heavy rules, numbered sections, unexpected rotations.",
    mood: ["raw", "editorial", "confident", "anti-design"],
    palette: {
      primary: "#111111",
      accent: "#E0371F",
      bg: "#F2EFE8",
      surface: "#FFFFFF",
      text: "#111111",
      muted: "#777777",
    },
    typography: {
      heading: "Space Grotesk",
      body: "IBM Plex Mono",
      headingWeight: 700,
      bodyWeight: 400,
      headingCase: "uppercase",
    },
    layoutDNA:
      "Asymmetric 12-column grid with visible column rules. Every section numbered (§01, §02). Huge headlines break the grid; one element per section rotated -2deg or 2deg. Body copy in mono. Heavy 2px black rules between sections. CTA is a solid black rectangle, no radius.",
    bestFor: ["creative studios", "record labels", "festivals", "galleries"],
  },
  {
    id: "warm-organic",
    name: "Warm Organic",
    blurb: "Terracotta and sage, rounded geometry, human and approachable.",
    mood: ["inviting", "earthy", "optimistic", "crafted"],
    palette: {
      primary: "#2F3E2E",
      accent: "#C96A4B",
      bg: "#FAF4EC",
      surface: "#FFFFFF",
      text: "#2B2A26",
      muted: "#7A6F63",
    },
    typography: {
      heading: "Fraunces",
      body: "DM Sans",
      headingWeight: 600,
      bodyWeight: 400,
      headingStyle: "italic",
    },
    layoutDNA:
      "Soft corners (24px radius) on every surface. Hero uses a split with a framed photograph on one side and Fraunces italic on the other. Buttons are terracotta pill shapes. Section backgrounds alternate cream and a slightly deeper sand. Sage used only for secondary accents.",
    bestFor: ["wellness", "hospitality", "food & beverage", "lifestyle DTC"],
  },
  {
    id: "atmospheric-glass",
    name: "Atmospheric Glass",
    blurb: "Deep indigo gradient, frosted cards, soft luminous edges.",
    mood: ["dreamy", "immersive", "technical-future", "cinematic"],
    palette: {
      primary: "#FFFFFF",
      accent: "#7FB5FF",
      bg: "#0B1020",
      surface: "rgba(255,255,255,0.04)",
      text: "#E8ECF5",
      muted: "#8891AD",
    },
    typography: {
      heading: "Space Grotesk",
      body: "Inter",
      headingWeight: 500,
      bodyWeight: 400,
    },
    layoutDNA:
      "Background is a slow-moving radial gradient (indigo to near-black). Content sits on backdrop-blur cards with 1px inner glow. Section dividers are fade-to-transparent hairlines. Buttons have soft outer glow; primary uses cyan-to-violet gradient. Typography is tight tracking, no uppercase.",
    bestFor: ["AI startups", "creative tooling", "film/audio", "fintech"],
  },
  {
    id: "clean-utility",
    name: "Clean Utility",
    blurb: "Pure white, dense, neutral. Trust through restraint.",
    mood: ["trustworthy", "efficient", "informational", "institutional"],
    palette: {
      primary: "#0A66FF",
      accent: "#0A66FF",
      bg: "#FFFFFF",
      surface: "#F6F8FB",
      text: "#0E1116",
      muted: "#57606A",
    },
    typography: {
      heading: "Inter",
      body: "Inter",
      headingWeight: 600,
      bodyWeight: 400,
    },
    layoutDNA:
      "Narrow center column (960px). No hero image — headline + one-line subtitle + single primary button. Feature sections are 3-column with tiny monochrome icons and one-line descriptions. All CTAs rectangular with 6px radius. Dividers are 1px at 6% black. Dense.",
    bestFor: ["B2B SaaS", "developer tools", "healthcare portals", "finance"],
  },
  {
    id: "oversized-type",
    name: "Oversized Typographic",
    blurb: "Typography as the entire design system. Imagery optional.",
    mood: ["bold", "expressive", "opinionated", "confident"],
    palette: {
      primary: "#111111",
      accent: "#FF5A3C",
      bg: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#111111",
      muted: "#5C5C5C",
    },
    typography: {
      heading: "Archivo",
      body: "Inter",
      headingWeight: 900,
      bodyWeight: 400,
      headingCase: "normal",
    },
    layoutDNA:
      "Hero headline at ~16vw, line-height 0.9, filling the viewport. Subsequent sections use one massive verb-first statement each. Imagery appears only as small in-line tokens. One color accent used exactly 3 times per page. Buttons are plain underlined text.",
    bestFor: ["agencies", "portfolios", "manifestos", "bold DTC"],
  },
  {
    id: "bold-color-monolith",
    name: "Bold Color Monolith",
    blurb: "A single saturated brand color saturates the entire page.",
    mood: ["vivid", "playful", "memorable", "unapologetic"],
    palette: {
      primary: "#FFFFFF",
      accent: "#0E1116",
      bg: "#F25C2B",
      surface: "rgba(255,255,255,0.08)",
      text: "#FFFFFF",
      muted: "rgba(255,255,255,0.7)",
    },
    typography: {
      heading: "Clash Display",
      body: "Inter",
      headingWeight: 600,
      bodyWeight: 400,
    },
    layoutDNA:
      "Entire page background is the accent color. Type is white. Surfaces are 8%-white translucent cards. Primary CTA inverts to black on white. Sections separated only by whitespace and scale shifts — no rules. Imagery silhouetted / cut out against the color field.",
    bestFor: ["consumer apps", "events", "beverage", "youth brands"],
  },
  {
    id: "saas-split",
    name: "SaaS Split",
    blurb: "Professional 50/50 hero, gradient accents, dependable.",
    mood: ["professional", "modern", "explanatory", "conversion-focused"],
    palette: {
      primary: "#5B4BFF",
      accent: "#12D3A5",
      bg: "#FFFFFF",
      surface: "#F4F3FF",
      text: "#101223",
      muted: "#5A5F7A",
    },
    typography: {
      heading: "Inter",
      body: "Inter",
      headingWeight: 700,
      bodyWeight: 400,
    },
    layoutDNA:
      "Hero is 50/50 split: copy on left, product visual on right inside a rounded card with soft shadow and a violet-to-teal gradient behind it. Feature sections alternate image-left / image-right. Primary CTA is violet with soft glow. Pricing section included by default.",
    bestFor: ["SaaS", "productivity", "developer platforms", "analytics"],
  },
  {
    id: "prestige-hospitality",
    name: "Prestige Hospitality",
    blurb: "Warm off-white, deep emerald, italic serif ligatures.",
    mood: ["refined", "welcoming", "considered", "classical"],
    palette: {
      primary: "#0F3B2E",
      accent: "#B59250",
      bg: "#F4F1EA",
      surface: "#FFFFFF",
      text: "#1C1B17",
      muted: "#776E60",
    },
    typography: {
      heading: "Fraunces",
      body: "DM Sans",
      headingWeight: 500,
      bodyWeight: 400,
      headingStyle: "italic",
    },
    layoutDNA:
      "Hero headline in italic Fraunces with swash ligatures, centered, over a single large photograph. Navigation uses letter-spaced small caps. Sections feature oversized image + short caption layout. Gold used sparingly for rules and numerals. Ample padding everywhere.",
    bestFor: ["hotels", "restaurants", "wineries", "private clubs"],
  },
  {
    id: "technical-data-grid",
    name: "Technical Data Grid",
    blurb: "Monospace-driven, terminal-green accent, information density.",
    mood: ["technical", "precise", "engineering", "developer-first"],
    palette: {
      primary: "#E6EDE8",
      accent: "#2BE07A",
      bg: "#0B0F10",
      surface: "#11171A",
      text: "#E6EDE8",
      muted: "#6F8076",
    },
    typography: {
      heading: "JetBrains Mono",
      body: "JetBrains Mono",
      headingWeight: 500,
      bodyWeight: 400,
    },
    layoutDNA:
      "Full-bleed grid overlay (1px lines at 6% opacity). Every label is bracketed like [docs] or //run. Status dots (●) next to section titles. Charts and code blocks are first-class content. Primary CTA uses terminal-green border + glow on hover.",
    bestFor: ["dev tools", "infra", "security", "trading platforms"],
  },
  {
    id: "sculptural-minimal",
    name: "Sculptural Minimal",
    blurb: "Ink on bone. One monumental statement per screen.",
    mood: ["sparse", "gallery", "contemplative", "timeless"],
    palette: {
      primary: "#141210",
      accent: "#141210",
      bg: "#F2EEE6",
      surface: "#FFFFFF",
      text: "#141210",
      muted: "#8A8376",
    },
    typography: {
      heading: "Canela",
      body: "Inter",
      headingWeight: 300,
      bodyWeight: 400,
    },
    layoutDNA:
      "One headline per viewport. Vast vertical rhythm. No color except ink black on bone. Imagery appears full-bleed with thin ink captions below. CTA is a single underlined word. Footer is one line of small caps.",
    bestFor: ["galleries", "museums", "design studios", "high-end editorial"],
  },
];

export const getTemplate = (id: string): DesignTemplate | undefined =>
  DESIGN_TEMPLATES.find((t) => t.id === id);
